version: '3.9'
services:
  pg-server-14:
    container_name: ${PGHOST}
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql:/var/lib/postgresql/data

  pg-client:
    environment:
      PGDATABASE: postgres
      PGHOST: ${PGHOST}
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: ${PGPASSWORD}
    build:
      context: .
      dockerfile: pg-client.dockerfile
    restart: no
